# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonaccitest',
            name='latency',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
